### ISSUE TITLE
Need to add Scroll To Top Button 

### ISSUE THREAD

**Issue by antonmak1** [hmpl-lang/hmpl-lang.github.io#9]
In vuepress enable backToTop and make a custom svg instead of the default one. Config.js here - https://github.com/hmpl-lang/hmpl-lang.github.io/blob/master/docs/.vuepress/config.js

**Comment by rustedusted** [comment]
i can work on this if you're okay with it :D

**Comment by antonmak1** [comment]
@rustedusted Hello! Sorry, it seems to have already been taken into work by @drippypop

**Comment by antonmak1** [comment]
@rustedusted Thanks a lot!

**Comment by rustedusted** [comment]
oh alright no problem if there's any other issue i can contribute to please do tell me

**Comment by antonmak1** [comment]
@rustedusted Thank you! Yes, of course there are, here is a list of open issues - https://github.com/hmpl-lang/hmpl/issues
